//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class iwn_orders
    {
        public int id { get; set; }
        public int amount { get; set; }
        public decimal total { get; set; }
        public int productsID { get; set; }
        public int buyersID { get; set; }
        public int deliveryID { get; set; }
    
        public virtual iwn_buyers iwn_buyers { get; set; }
        public virtual iwn_products iwn_products { get; set; }
        public virtual iwn_delivery iwn_delivery { get; set; }
    }
}
