//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class iwn_products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iwn_products()
        {
            this.iwn_orders = new HashSet<iwn_orders>();
        }
    
        public int id { get; set; }
        public System.Guid guid { get; set; }
        public string articul { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public string currency { get; set; }
        public int producerID { get; set; }
        public int productTypeID { get; set; }
    
        public virtual iwn_producers iwn_producers { get; set; }
        public virtual iwn_productType iwn_productType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iwn_orders> iwn_orders { get; set; }
    }
}
